/*
Copyright (c) 2012-2015, Coherent Labs AD
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of Coherent UI nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coherentlabs_ui_CoherentWebViewClient */

#ifndef _Included_com_coherentlabs_ui_CoherentWebViewClient
#define _Included_com_coherentlabs_ui_CoherentWebViewClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_coherentlabs_ui_CoherentWebViewClient
 * Method:    notifyOnPageStarted
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coherentlabs_ui_CoherentWebViewClient_notifyOnPageStarted
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coherentlabs_ui_CoherentWebViewClient
 * Method:    notifyOnPageError
 * Signature: (ILjava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coherentlabs_ui_CoherentWebViewClient_notifyOnPageError
  (JNIEnv *, jobject, jint, jstring, jint, jstring);

/*
 * Class:     com_coherentlabs_ui_CoherentWebViewClient
 * Method:    notifyOnPageFinished
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coherentlabs_ui_CoherentWebViewClient_notifyOnPageFinished
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coherentlabs_ui_CoherentWebViewClient
 * Method:    shouldStartLoad
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_coherentlabs_ui_CoherentWebViewClient_shouldStartLoad
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coherentlabs_ui_CoherentWebViewClient
 * Method:    triggerNativeCode
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coherentlabs_ui_CoherentWebViewClient_triggerNativeCode
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
